name: Release
on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types: [completed]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js, NPM
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - name: apt install
        run: sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_OPTIONS: --openssl-legacy-provider
        run: npx semantic-release
