name: Test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - name: apt install
        run: sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: npm install
        run: npm ci
      - name: npm test
        run: npm test
